### Post new import
POST http://localhost:44373/import HTTP/1.1
Content-Type: multipart/form-data;boundary=----boundary

----boundary
Content-Disposition: form-data; name="token"

00000-11111-22222
----boundary 
Content-Disposition: form-data; name="facilityid"

2345
----boundary 
Content-Disposition: form-data; name="period"

2020-09
----boundary 
Content-Disposition: form-data; name="file"; filename="AFaclity_Purchase_09_2020.csv" 

ABC #,Product Description,NDC,Average Invoice Price,Shipped Qty,Report Qty,Total Ext Cost,Account Type
10148276,KEYTRUDA 100MG/4ML SDV SOL ASD,,3373.63,38,0.77,128197.94,340B
10001566,REMICADE 100 MG VL,0,335.67,270,5.48,90630.9,340B
10174900,OCREVUS 300MG/10ML SDV ASD,50242-0150-01,non-valid,4,0.08,48066.76,340B
10148529,NEULASTA ONPRO KIT 6MG/0.6ML ASD,55513-0192,2355.91,non-valid,0.36,42406.38,340B
10209175,ANDEXXA FACTOR XA 4X200MG VL ASD,69853010201,21159.6,2,0.04,non-valid,340B
10183961,OPDIVO 240MG 24ML VL ASD,3373413,4625.93,9,0.18,41633.37,340B
----boundary

### Get progress
GET http://localhost:44373/progress?uploadid=11111111-33b3-44fb-76b2-08d866c9db60&token=00000-11111-22222

### Get all results
GET http://localhost:44373/results

### Get all results with uploadid paramerter (not used by JSON-Server)
GET http://localhost:44373/results?uploadid=11111111-33b3-44fb-76b2-08d866c9db60
