### Get all results
GET http://localhost:44373/results

### Get all results with uploadid paramerter (not used by JSON-Server)
GET http://localhost:44373/results?uploadid=f778c3e4-33b3-44fb-76b2-08d866c9db60

### Insert new result
POST http://localhost:44373/results HTTP/1.1
content-type: application/json

{"type": "warning", "message": "test warning",  "row": 1, "column": 1}
